name: terraform-prodiver-okta-s3-serve
on:
  push:
    branches: ['master']
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
  workflow_dispatch:

jobs:
  CI:
    env:
      SLACK_CHANNEL: deployments
      S3_BUCKET_CLI: infralight-templates-public
    name: "forked terraform-provider-okta"
    runs-on: ubuntu-latest
    steps:
    - name: Prod check
      run: |
        echo "SLACK_CHANNEL=prod-${{ env.SLACK_CHANNEL }}" >> $GITHUB_ENV
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - run: goimports -w .
    - run: go mod tidy  
    - name: Build Linux
      run: make build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.PROD_REGION }}
    - name: Upload files
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude='*' --include='terraform-provider-okta*'
      env:
        DEST_DIR: 'terraform-provider-okta'
        AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
    - name: Slack Notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://assets-global.website-files.com/5d514fd9493b0575f03520bd/5d8e0b39fd776a3c238e8753_icons8_infinity_large_filled_2.svg
        SLACK_MESSAGE: "forked terraform-provider-okta successfully deployed from ${{ github.ref }}"
        SLACK_TITLE:  "forked terraform-provider-okta deployment notification"
        SLACK_USERNAME: cicdBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
